import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import * as styles from '../styles/Cards.module.css';

export default function Home({ beers }) {
  //const { asPath } = useRouter();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by xxx" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        <Link href="/beers">
          <a>Punk APIs beers</a>
        </Link>
      </h1>

      <div className={styles.cardContainer}>
        {beers.map((beer) => {
          return (
            <div key={beer.id} className={styles.card}>
              <Link href={`/beers/${beer.id}`}>
                <a>
                  <h2>{beer.name}</h2>
                </a>
              </Link>
              <p>{beer.tag}</p>
              <div style={{ maxWidth: '100px' }}>
                {beer.image && (
                  <Image
                    src={beer.image}
                    alt={beer.name}
                    width="100%"
                    height="100%"
                    layout="responsive"
                    objectFit="contain"
                    placeholder="blur"
                    blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mM89R8AApkBy17XrZoAAAAASUVORK5CYII="
                  />
                )}
              </div>
            </div>
          );
        })}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const req1 = await fetch('https://api.punkapi.com/v2/beers/random');
  const req2 = await fetch('https://api.punkapi.com/v2/beers/random');
  const req3 = await fetch('https://api.punkapi.com/v2/beers/random');

  const res = await Promise.all([req1.json(), req2.json(), req3.json()]);
  const flat = [...res].flat();

  const data = flat.map((b) => {
    return { id: b.id, name: b.name, image: b.image_url, tag: b.tagline };
  });

  return {
    props: { beers: data },
  };
}
