import { useState, useEffect } from 'react';
import { DebounceInput } from 'react-debounce-input';
import { motion } from 'framer-motion';
import useSWR from 'swr';
import usePairings from '../hooks/usePairings';

import { getRandomBeers } from '../lib/getRandomBeers';
import { spring } from '../lib/anim';

import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card';

import * as styles from '../styles/Home.module.css';

export default function Home() {
  // fetch random beers
  const { data, error } = useSWR(
    'https://api.punkapi.com/v2/beers/random',
    getRandomBeers
  );

  // food pairing
  const [query, setQuery] = useState('');
  const { pairings } = usePairings(query);

  const handleChange = (e) => {
    setQuery(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by xxx" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.hero}>
        <h1 className={styles.title}>
          The <span>Brewdog</span> catalogue
        </h1>

        <div className={styles.image}>
          <Image
            src="/dog-logo.png"
            alt="brew dog logo"
            width="100%"
            height="100%"
            layout="responsive"
            objectFit="contain"
            placeholder="blur"
            blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mM89R8AApkBy17XrZoAAAAASUVORK5CYII="
          />
        </div>

        <p className={styles.intro}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas
          accumsan lacus a mattis dapibus. Praesent pretium aliquet cursus. Nunc
          sagittis nisl ac euismod sagittis. Mauris at quam faucibus nibh
          accumsan bibendum vel at nisi. Suspendisse faucibus vulputate turpis,
          vel pretium enim pharetra sit amet.
        </p>
      </section>

      <section className={styles.pairings}>
        <div className={styles.divider}>
          <h2>Find a perfect match!</h2>
          <p>
            Mauris at quam faucibus nibh accumsan bibendum vel at nisi.
            Suspendisse faucibus vulputate turpis, vel pretium enim pharetra sit
            amet.
          </p>

          <DebounceInput
            minLength={1}
            debounceTimeout={500}
            onChange={handleChange}
            placeholder="Try typing beef or curry..."
            value={query}
          />

          {pairings.length ? (
            <motion.ul layout transition={spring}>
              {pairings.map((beer, id) => (
                <Link href={`/beers/${beer.id}`} key={id}>
                  <a>
                    <h3>{beer.name}</h3>
                  </a>
                </Link>
              ))}
            </motion.ul>
          ) : (
            <motion.h3
              layout
              transition={{
                opacity: { ease: 'linear' },
                layout: { duration: 0.3 },
              }}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
            >
              No matches
            </motion.h3>
          )}
        </div>
      </section>

      <section className={styles.random}>
        {error && <h2>Failed to load</h2>}
        {!data && !error && <h2>Loading...</h2>}
        {data && (
          <>
            <h2>...three random beers</h2> <Card beers={data} />
          </>
        )}
      </section>
    </>
  );
}
